spring:
  application:
    name: inatel-back-end-test
  datasource:
    url: jdbc:mysql://localhost:3306/stock?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

info:
  app: Inatel Back end test
  website: https://inatel.br/home/